/**
 * All user-facing copy for Flow B in Hindi (Devanagari).
 * STRICT RULE: No banned words (CPM, CTR, CAC, Impressions, Conversions, Funnel,
 * Placement, Pixel, Reach, Inquiries, Call to action, Audience, Targeting,
 * KYC, Aadhaar, आधार नंबर, 100% सुरक्षित, सबसे ज़्यादा चुना गया).
 * Allowed Latin words: "नवभारत ऐड्स", UPI, OTP, WhatsApp, GST, PAN, ₹, plus UPI app names.
 */

export const STRINGS = {
  brand: {
    name: 'नवभारत ऐड्स',
    adsPart: 'ऐड्स',
    navbharat: 'नवभारत',
  },
  common: {
    back: 'वापस जाएँ',
    help: 'मदद',
    save: 'सेव करें',
    next: 'आगे बढ़ें',
    stepPill: (step) => `स्टेप ${step}/6`,
    adTag: 'विज्ञापन',
    reportAd: 'विज्ञापन की रिपोर्ट करें',
    reportReceived: 'रिपोर्ट मिल गई, धन्यवाद',
    verified: 'वेरिफाइड',
    optionalHint: '(बाद में भी भर सकते हैं)',
    cancel: 'रद्द करें',
    close: 'बंद करें',
    change: 'बदलें',
    rupees: '₹',
    perDay: '/दिन',
    days: 'दिन',
    totalWithGst: '(GST सहित)',
    inclusiveGst: 'GST सहित',
    emptyMediaPlaceholder: 'फोटो जोड़ने पर यहाँ दिखेगी',
    emptyHeadlinePlaceholder: 'आपकी हेडलाइन यहाँ दिखेगी',
  },
  intro: {
    title: 'अपने शहर में कारोबार बढ़ाएँ',
    subtitle: 'सीधे स्थानीय ग्राहकों तक, सिर्फ ₹100 से',
    badge1: 'अपने शहर में',
    badge2: 'सिर्फ ₹100 से',
    badge3: '5 मिनट में तैयार',
    reassurance: 'पहले विज्ञापन देखें, पेमेंट आख़िर में',
    ctaCreate: 'विज्ञापन बनाएँ',
    ctaOtpLogin: 'OTP से लॉगिन करें',
    ctaCompleteShop: 'अपनी दुकान की जानकारी भरें',
    ctaDashboard: 'डैशबोर्ड पर जाएँ',
    newAdSecondary: 'नया विज्ञापन बनाएँ',
    viewSample: 'सैंपल विज्ञापन देखें',
    hasAccountLogin: 'अकाउंट है? लॉगिन करें',
    sampleSheetTitle: 'आपका विज्ञापन ऐसा दिखेगा',
    sampleShopName: 'ब्रू बैठक',
    sampleHeadline: 'ब्रू बैठक · आपके शहर में ताज़ा चाय और नाश्ता',
    sampleBtnLabel: 'कॉल करें',
    sampleCloseAndCreate: 'अपना विज्ञापन बनाएँ',
  },
  login: {
    title: 'मोबाइल नंबर डालें',
    subtitle: 'आपके नंबर पर 6 अंकों का OTP आएगा',
    phoneLabel: 'मोबाइल नंबर',
    phonePrefix: '+91',
    phoneError: 'कृपया मान्य मोबाइल नंबर डालें (6-9 से शुरू)',
    sendOtp: 'OTP भेजें',
    sendingOtp: 'भेजा जा रहा है…',
    changeNumber: 'बदलें',
    otpLabel: '6 अंकों का OTP डालें',
    otpError: 'OTP सही नहीं है. दोबारा डालें',
    verifyBtn: 'वेरिफ़ाई करें',
    resendIn: (sec) => `दोबारा भेजें 00:${sec < 10 ? `0${sec}` : sec}`,
    resendBtn: 'OTP दोबारा भेजें',
    noOtpHelp: 'OTP नहीं आया? मदद लें',
  },
  shop: {
    title: 'आपकी दुकान की जानकारी',
    subtitle: 'नाम, श्रेणी और पिन कोड ज़रूरी हैं',
    verifiedPhoneLine: (phone) => `✓ ${phone} वेरिफाइड`,
    logoLabel: 'लोगो जोड़ें',
    logoUploadError: 'फोटो जुड़ नहीं पाई, दोबारा कोशिश करें',
    nameLabel: 'दुकान का नाम',
    namePlaceholder: 'जैसे: शर्मा स्वीट्स',
    nameError: 'कृपया दुकान का नाम डालें',
    categoryLabel: 'दुकान किस चीज़ की है?',
    categoryPlaceholder: 'श्रेणी चुनें',
    categorySheetTitle: 'दुकान की श्रेणी चुनें',
    pincodeLabel: 'पिन कोड',
    pincodePlaceholder: '6 अंकों का पिन कोड',
    pincodeNotFound: 'यह पिन कोड नहीं मिला. अपना शहर चुनें',
    pickCityBtn: 'शहर चुनें',
    addressLabel: 'पता या इलाका',
    addressPlaceholder: 'जैसे: विजय नगर',
    ownerLabel: 'मालिक का नाम',
    ownerPlaceholder: 'जैसे: राजेश शर्मा',
    emailLabel: 'ईमेल',
    emailPlaceholder: 'जैसे: info@dukaan.com',
    emailReason: 'बिल यहाँ भेजेंगे',
    emailError: 'कृपया सही ईमेल डालें (जैसे info@dukaan.com)',
    missingPincodeHint: 'पिन कोड डालना बाकी है',
    missingCategoryHint: 'दुकान की श्रेणी चुनना बाकी है',
    missingNameHint: 'दुकान का नाम डालना बाकी है',
  },
  goal: {
    title: 'आप क्या चाहते हैं?',
    subtitle: 'अपना मकसद चुनें',
    btnPreviewNotice: (btnText) => `आपके विज्ञापन में बटन होगा: ${btnText}`,
  },
  format: {
    title: 'विज्ञापन का प्रकार चुनें',
    subtitle: 'सबसे आसान वाला पहले से चुना है',
    tabs: {
      all: 'सभी',
      reel: 'रील',
      newsFeed: 'न्यूज़ फ़ीड',
    },
    easiestBadge: 'सबसे आसान',
    whereInFeed: 'न्यूज़ फ़ीड में दिखेगा',
    whereInReel: 'रील में दिखेगा',
    whereLabel: 'यह कहाँ दिखेगा',
    toastFormatChanged: 'प्रकार बदलने से पुरानी फाइल हट गई',
  },
  ad: {
    title: 'आपका विज्ञापन बनाएँ',
    subtitle: 'फोटो जोड़ें और दो लाइन लिखें',
    compactPreviewLabel: 'प्रीव्यू देखें',
    gridMediaHint: 'कम से कम 2 फोटो चाहिए, 4 हों तो बेहतर',
    carouselAddSlide: '+ स्लाइड जोड़ें',
    uploadTip: 'साफ़ और रोशनी वाली फोटो चुनें',
    photoCleanSuccess: 'फोटो साफ़ है ✓',
    photoSmallWarn: 'फोटो छोटी है, साफ़ फोटो बेहतर रहेगी',
    videoAspectError: 'यह वीडियो आड़ा है. कृपया खड़ा (मोबाइल जैसा) वीडियो डालें',
    videoLengthError: 'वीडियो अधिकतम 60 सेकंड का होना चाहिए',
    videoSizeError: 'वीडियो साइज़ 50MB से कम होना चाहिए',
    uploadErrorMsg: 'फोटो अपलोड नहीं हुई',
    retryUpload: 'दोबारा कोशिश करें',
    addPhotoSlot: 'फोटो जोड़ें',
    headlineLabel: 'हेडलाइन',
    headlinePlaceholder: 'जैसे: शर्मा स्वीट्स · दिवाली की मिठाई',
    headlineSuggestion: (shop, city) => `सुझाव: ${shop} · ${city}`,
    descLabel: 'विवरण',
    descPlaceholder: 'जैसे: सभी ब्रांड के जूते, ₹499 से शुरू',
    buttonLabel: 'बटन',
    whatsappLabel: 'WhatsApp नंबर',
    phoneFieldLabel: 'फोन नंबर',
    linkLabel: 'लिंक',
    linkPlaceholder: 'https://...',
    sponsorLabel: 'प्रायोजक',
    policyBlockedError: 'यह शब्द विज्ञापन नियमों में मना है',
    policyClaimWarn: 'इस दावे को साबित करना पड़ सकता है',
    viewRulesLink: 'विज्ञापन के नियम देखें',
    missingHeadline: 'हेडलाइन डालना बाकी है',
    missingMedia: 'कम से कम 2 फोटो चाहिए',
    missingSingleMedia: '1 फोटो अपलोड करना बाकी है',
    missingVideo: 'वीडियो अपलोड करना बाकी है',
    missingContact: 'संपर्क जानकारी डालना बाकी है',
    resubmitBtn: 'सेव करके दोबारा भेजें',
  },
  area: {
    title: 'विज्ञापन कहाँ दिखाना है?',
    subtitle: 'आपकी दुकान के आसपास के शहरों में दिखेगा',
    mapDisclaimer: 'नक्शा सिर्फ़ अंदाज़े के लिए है',
    distanceTitle: 'दुकान से दूरी',
    distanceValue: (km) => `${km} किमी`,
    resetDistance: '10 किमी पर वापस',
    citiesVisibleLabel: 'इन शहरों में दिखेगा',
    singleCityCovered: 'आपका पूरा शहर कवर हो रहा है',
    addMoreCitiesBtn: '+ और शहर या राज्य जोड़ें',
    reachCardTitle: 'आपके इलाके में कुल पाठक',
    reachRangeFormat: (lo, hi) => `लगभग ${lo}–${hi}`,
    estimateBadge: 'अनुमान',
    estimateTestNote: '(टेस्ट के लिए अनुमान)',
    audienceAccordionTitle: 'और विकल्प: उम्र और लिंग',
    audienceSummaryAll: 'सभी पाठक · सभी उम्र',
    genderLabel: 'लिंग',
    genderMale: 'पुरुष',
    genderFemale: 'महिला',
    genderAll: 'सभी पाठक',
    ageLabel: 'उम्र',
    ageMinError: 'कम से कम एक उम्र चुनें',
    wideAreaBanner: 'बड़े इलाके में दिखाने के लिए ज़्यादा बजट लगेगा',
    measuredFromCityCenter: 'शहर के बीच से नापा गया',
  },
  citySheet: {
    searchPlaceholder: 'शहर खोजें',
    selectAllState: (state) => `पूरा ${state} चुनें`,
    doneBtn: (count) => `${count} शहर चुने, हो गया`,
  },
  budget: {
    title: 'बजट और दिन चुनें',
    subtitle: 'रोज़ कितना खर्च करना है?',
    recommendedBadge: 'सुझाया गया',
    customTitle: 'अपना चुनें',
    customTagline: 'स्लाइडर से तय करें',
    dailyCapLine: (amt) => `आप इससे ज़्यादा कभी नहीं देंगे: ₹${amt} प्रतिदिन`,
    reachWillDeliver: 'आपके विज्ञापन तक पहुँचेंगे',
    reachRangeLine: (lo, hi) => `इतने बजट में लगभग ${lo}–${hi} पाठक`,
    audienceLimitedNote: 'आपके इलाके के लगभग सभी पाठक तक पहुँच जाएँगे. कम बजट भी काफ़ी है',
    audienceLimitedChip: (amt) => `₹${amt}/दिन चुनें`,
    budgetLimitedNote: 'बजट बढ़ाने पर ज़्यादा पाठक तक पहुँचेंगे',
    startModeImmediate: 'रिव्यू के बाद अपने आप शुरू',
    startModeScheduled: 'बाद में शुरू करें',
    viewBill: 'बिल देखें',
    totalWithGstSticky: (amt) => `कुल ₹${amt} (GST सहित)`,
  },
  billSheet: {
    title: 'खर्च का ब्यौरा',
    budgetLine: (daily, days, sub) => `विज्ञापन बजट ₹${daily} × ${days} दिन = ₹${sub}`,
    gstLine: (gst) => `+18% GST ₹${gst}`,
    totalLine: (tot) => `कुल ₹${tot}`,
    invoiceNote: 'GST इनवॉइस पेमेंट के बाद मिलेगी',
    whatIsGstLink: 'GST क्या है?',
  },
  gstInfoSheet: {
    title: 'GST की जानकारी',
    body: 'GST सरकार को जाने वाला कर है, जो आपके बजट पर जुड़ता है.',
  },
  review: {
    title: 'विज्ञापन जाँचें और पेमेंट करें',
    banner: (citiesText, days) => `आपका विज्ञापन ${citiesText} में ${days} दिन तक दिखेगा.`,
    previewCaption: 'विज्ञापन ऐसा दिखेगा',
    rowGoalFormat: 'उद्देश्य व प्रकार',
    rowArea: 'इलाका',
    rowAudience: 'किन लोगों को',
    rowBudget: 'बजट और दिन',
    rowShop: 'दुकान',
    editGoal: 'उद्देश्य बदलें',
    editFormat: 'प्रकार बदलें',
    identityTitle: 'एक बार पहचान की जाँच',
    identitySubtitle: 'ताकि पाठक सुरक्षित रहें और आपका विज्ञापन जल्दी पास हो',
    gstTab: 'GST नंबर',
    panTab: 'PAN नंबर',
    aadhaarDisabledTab: 'आधार (DigiLocker से) · जल्द आ रहा है',
    checkIdentityBtn: 'जाँच करें',
    checkingIdentity: 'जाँचा जा रहा है…',
    identityInvalidError: 'यह नंबर नहीं मिला. दोबारा जाँचें',
    identityVerifiedLine: (masked) => `✓ पहचान की जाँच पूरी · ${masked}`,
    neitherHelpLink: 'दोनों नहीं हैं?',
    optionalBillingEmail: 'ईमेल (बिल के लिए, वैकल्पिक)',
    footnote: 'पेमेंट के बाद विज्ञापन रिव्यू में जाएगा. हम आपको खबर देंगे.',
    payBtn: (amt) => `₹${amt} पेमेंट करें`,
    verifyIdentityFirstToast: 'पहले पहचान की जाँच पूरी करें',
  },
  payment: {
    title: 'पेमेंट करें',
    subGst: 'GST सहित',
    googlePay: 'गूगल पे',
    phonePe: 'फ़ोनपे',
    paytm: 'पेटीएम',
    bhim: 'भीम',
    otherUpiTitle: 'दूसरी UPI ID से पेमेंट करें',
    upiPlaceholder: 'जैसे: mobile@upi',
    upiInvalid: 'UPI ID सही नहीं है',
    payUpiBtn: 'पेमेंट करें',
    safetyLine: 'पेमेंट आपके UPI ऐप में होगा',
    processingTitle: 'पेमेंट हो रहा है…',
    processingSubtitle: 'ऐप बंद न करें',
    pendingTitle: (app) => `${app} में पेमेंट पूरा करें`,
    pendingSubtitle: 'कृपया अपने ऐप में मंज़ूरी दें',
    failedTitle: 'पेमेंट नहीं हुआ',
    failedSubtitle: 'अगर पैसे कट गए हों तो 24 घंटे में वापस आ जाएँगे',
    retryBtn: 'दोबारा कोशिश करें',
    pickAnotherAppBtn: 'दूसरा ऐप चुनें',
    successTitle: 'पेमेंट सफल!',
  },
  status: {
    title: 'आपका विज्ञापन',
    orderHeader: (orderId, amt) => `ऑर्डर #${orderId} · ₹${amt} · पेमेंट हो गया`,
    step1: 'पेमेंट हुआ ✓',
    step2: 'रिव्यू में',
    step3: 'मंज़ूर',
    step4: 'लाइव',
    inReviewTitle: 'आपका विज्ञापन जाँचा जा रहा है',
    inReviewSubtitle: 'मंज़ूर होते ही हम आपको बताएँगे',
    whatsappUpdatesToggle: 'WhatsApp पर खबर पाएँ',
    extraCheckNotice: 'इस श्रेणी के लिए अतिरिक्त जाँच हो रही है',
    approvedTitle: 'बधाई! आपका विज्ञापन मंज़ूर हो गया',
    startImmediate: 'रिव्यू के बाद शुरू हो रहा है',
    startScheduled: (dateStr) => `${dateStr} से शुरू होगा`,
    scheduledTitle: (dateStr) => `शुरू होगा: ${dateStr}`,
    needsChangesTitle: 'बदलाव चाहिए',
    fixAndResubmitBtn: 'ठीक करें और दोबारा भेजें',
    liveTitle: 'आपका विज्ञापन चल रहा है',
    dashboardBtn: 'डैशबोर्ड देखें',
    needSupportBtn: 'मदद लें',
  },
  dashboard: {
    title: 'विज्ञापन डैशबोर्ड',
    newAdBtn: '+ नया विज्ञापन',
    identityVerifiedChip: '✓ पहचान की जाँच पूरी',
    emptyTitle: 'अभी कोई विज्ञापन नहीं है',
    emptyCreateBtn: 'पहला विज्ञापन बनाएँ',
    daysRemaining: (total, left) => `${total} दिन · ${left} दिन बाकी`,
    spendLine: (spent, subtotal) => `खर्च ₹${spent} / ₹${subtotal}`,
    metricViews: 'कितनी बार दिखा',
    metricClicks: 'क्लिक',
    metricTapEngagement: 'WhatsApp या कॉल टैप',
    metricTapCtrs: 'लिंक टैप',
    metricTapReach: 'जानकारी टैप',
    metricSpent: 'खर्च',
    dataComing: 'डेटा आ रहा है',
    sampleDataChip: 'सैंपल डेटा',
    btnPause: 'रोकें',
    btnResume: 'चालू करें',
    btnEditBudget: 'बजट बदलें',
    btnAnalytics: 'एनालिटिक्स',
    btnEditAd: 'विज्ञापन बदलें',
    btnRerun: 'फिर से चलाएँ',
    fixAndResubmit: 'ठीक करें और दोबारा भेजें',
    adRecheckNotice: 'बदलाव के बाद दोबारा जाँच होगी',
    accountLine: (phone) => `अकाउंट: +91 ${phone}`,
    profileMenuShop: 'दुकान की जानकारी बदलें',
    profileMenuBilling: 'बिल और पेमेंट',
    profileMenuLogout: 'लॉगआउट',
    logoutConfirmTitle: 'लॉगआउट करना चाहते हैं?',
    logoutConfirmBtn: 'लॉगआउट',
  },
  editBudget: {
    title: 'बजट बदलें',
    remainingDaysCopy: (n) => `आज से बचे हुए ${n} दिनों के लिए नया रोज़ का बजट`,
    effectiveTomorrow: 'नया बजट कल से लागू होगा',
    additionalCostNotice: (amt) => `अतिरिक्त राशि ₹${amt} (GST सहित)`,
    payDifferenceBtn: (amt) => `₹${amt} पेमेंट करें`,
    saveBudgetBtn: 'नया बजट सेव करें',
  },
  billingSheet: {
    title: 'बिल और पेमेंट',
    noInvoices: 'अभी कोई इनवॉइस नहीं है',
    downloadInvoice: 'इनवॉइस डाउनलोड',
  },
  analytics: {
    title: 'विज्ञापन एनालिटिक्स',
    sampleDataNotice: 'सैंपल डेटा',
    spendProgress: (spent, subtotal) => `खर्च ₹${spent} / ₹${subtotal}`,
    daysLeft: (n) => `${n} दिन बाकी`,
  },
  adRules: {
    title: 'विज्ञापन के नियम',
    okSection: '✓ ठीक है',
    watchSection: '⚠ अतिरिक्त जाँच',
    bannedSection: '✗ मना है',
    footerNote: "प्रायोजित स्टोरी कार्ड पर दुकान का नाम और 'विज्ञापन' हमेशा दिखेगा",
    draftDisclaimer: 'यह नियम प्रारूप विधि एवं संचालन विभाग की मंज़ूरी के लिए है.',
  },
  helpSheet: {
    title: 'मदद चाहिए?',
    body: 'हमारी टीम से सीधे WhatsApp पर सहायता प्राप्त करें.',
    openWhatsapp: 'WhatsApp पर बात करें',
  },
  guardToast: {
    fillShopFirst: 'पहले दुकान की जानकारी भरें',
    draftRestored: 'आपका ड्राफ़्ट सेव है',
  },
};
